added optimize delta tables to support all delta tables
microsoft/semantic-link-labs pull request #386
Opened 2024-12-30 08:18 UTC by m-kovalsky

2025-01-07 16:46 UTC, eisber requested changes

2025-01-07 16:46 UTC, eisber commented on src/sempy_labs/_optimize.py
> +        deltaTable.optimize().executeCompaction()
why would you use the notebook instead of this? https://learn.microsoft.com/en-us/rest/api/fabric/lakehouse/background-jobs/run-on-demand-table-maintenance?tabs=HTTP

2025-01-09 08:51 UTC, m-kovalsky commented on src/sempy_labs/_optimize.py
> +        deltaTable.optimize().executeCompaction()
removed this function for now

2025-01-09 11:28 UTC, eisber commented on src/sempy_labs/_helper_functions.py
> +    workspace_id = path.split("abfss://")[1].split("@")[0]
in general I'd recommend to https://docs.python.org/3/library/urllib.parse.html

2025-01-09 11:28 UTC, eisber commented on src/sempy_labs/_optimize.py
> +        deltaTable.optimize().executeCompaction()
function is still there?

2025-01-09 19:28 UTC, m-kovalsky commented on src/sempy_labs/_helper_functions.py
> +    workspace_id = path.split("abfss://")[1].split("@")[0]
fixed

2025-01-09 19:28 UTC, m-kovalsky commented on src/sempy_labs/_optimize.py
> +        deltaTable.optimize().executeCompaction()
removed

2025-01-13 10:15 UTC, eisber approved these changes

2025-01-13 10:39 UTC, merged