M kovalsky/generatedlsemanticmodel
microsoft/semantic-link-labs pull request #63
Opened 2024-08-06 11:21 UTC by m-kovalsky

2024-08-06 14:19 UTC, eisber requested changes

2024-08-06 14:19 UTC, eisber commented on src/sempy_labs/directlake/_dl_helper.py
> +    while not success:
can you move the timeout into the while condition? makes it easier to read. also why use success = True if you break later? why not always break?

2024-08-07 06:41 UTC, m-kovalsky commented on src/sempy_labs/directlake/_dl_helper.py
> +    while not success:
success=True stops the while loop. if i don't put it there it will spin for a minute and keep adding and readding the same table repeatedly.

2024-08-07 08:18 UTC, m-kovalsky commented on src/sempy_labs/directlake/_dl_helper.py
> +    while not success:
added decorator function

2024-08-07 09:06 UTC, eisber approved these changes

2024-08-07 09:06 UTC, eisber commented on src/sempy_labs/_helper_functions.py
> +                    time.sleep(sleep_time)
can be for the next pr: remember the last exception and pass along w/ timeouterror. e.g. what happens if this fails due to some other reason

2024-08-07 09:06 UTC, eisber commented on src/sempy_labs/directlake/_dl_helper.py
> +    @retry(sleep_time=1, timeout_error_message="Function timed out after 1 minute")
checking every second seems a bit aggressive. maybe do 5?
also the error message is probably better to state: dyn_create_model function failed after timeout. you can generate the message by doing func.__name__

2024-08-07 11:52 UTC, m-kovalsky commented on src/sempy_labs/directlake/_dl_helper.py
> +    @retry(sleep_time=1, timeout_error_message="Function timed out after 1 minute")
i think 5 is too long. i tried that before and it makes it take longer on average.

2024-08-07 11:54 UTC, merged